spring.application.name=anunciosloc-server 

# Servidor
server.port=8080

spring.jackson.deserialization.fail-on-unknown-properties=false


# UDDI
uddi.server-url=http://localhost:9000
infra.group-prefix=D01

# PostgreSQL - Banco do AnunciosLoc
spring.datasource.url=jdbc:postgresql://localhost:5432/anuncio
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# URL do Kerberos Server (SOAP)
kerberos.soap.url=http://localhost:8085/ws/kerberos

# Logging
logging.level.com.anunciosloc.anunciosloc=DEBUG

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=300000
spring.cache.redis.cache-null-values=false
