spring.application.name=anunciosloc-server 

# Servidor
server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/anunciosloc_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.anunciosloc=DEBUG

# Configurações do Kerberos
kerberos.constante=AnunciosLoc2024
kerberos.hash.algoritmo=SHA-256