spring.application.name=infrastructura-server

# Porta REST — cada instância usa uma diferente
server.port=${INFRA_PORT:8081}

# Porta separada para o endpoint SOAP JAX-WS
infra.soap-port=${INFRA_SOAP_PORT:8091}

# Identidade desta infraestrutura
infra.nome=${INFRA_NOME:D01_Infrastructure1}


# URL pública desta instância (usada no registo UDDI)
infra.public-url=${INFRA_URL:http://localhost:8091}

# URL do servidor UDDI
uddi.server-url=${UDDI_URL:http://localhost:9000}

# URL do anunciosloc_server
anunciosloc.server-url=${ANUNCIOSLOC_URL:http://localhost:8080}

# Cria a BD automaticamente antes do Hibernate arrancar
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bd_infra1}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:kama2}

# URL da BD admin para criar a BD se não existir
spring.datasource.hikari.initialization-fail-timeout=-1


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=300000
spring.cache.redis.cache-null-values=false

# Banner e logs
spring.main.banner-mode=off
logging.level.com.uan.anunciosloc=DEBUG

heartbeat.interval=30000