spring.application.name=anunciosloc-server

# Servidor
server.port=8080

# PostgreSQL - Banco do AnunciosLoc
spring.datasource.url=jdbc:postgresql://localhost:5432/anuncioLoc
spring.datasource.username=postgres
spring.datasource.password=ToSpring@2026
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# URL do Kerberos Server (SOAP)
kerberos.soap.url=http://localhost:8081/ws/kerberos

# Logging
logging.level.com.anunciosloc.anunciosloc=DEBUG
