spring.application.name=infrastructura-server
# Porta — cada instância usa uma diferente
server.port=${INFRA_PORT:8081}


# Porta separada para o endpoint SOAP JAX-WS
infra.soap-port=${INFRA_SOAP_PORT:8091}

# Identidade desta infraestrutura
infra.nome=${INFRA_NOME:D01_Infrastructure1}
infra.capacidade=${INFRA_CAPACIDADE:100}
infra.bonus-entrega=${INFRA_BONUS:2}
infra.custo-post=${INFRA_CUSTO:1}

# URL publica desta instância(usada no registo UDDI)
infra.public-url=${INFRA_URL:http://localhost:8081}

# URL do servidor UDDI
uddi.server-url=${UDDI_URL:http://localhost:9000}

# URL do anunciosloc_server
anunciosloc.server-url=${ANUNCIOSLOC_URL:http://localhost:8080}

# Desliga o banner desnecessario
spring.main.banner-mode=off

# Log
logging.level.com.uan.anunciosloc=DEBUG