spring.application.name=kerberos-server

# Servidor
server.port=8085
server.address=localhost

# PostgreSQL - Banco do Kerberos
spring.datasource.url=jdbc:postgresql://localhost:5432/kerbero_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.anunciosloc.kerberos=DEBUG
logging.level.org.springframework.ws=DEBUG
logging.level.org.springframework.boot.web.servlet=DEBUG
logging.level.org.springframework.ws.server=DEBUG
logging.level.org.springframework.ws.soap=DEBUG

# Constante para derivação de chaves
kerberos.constante=AnunciosLoc2024
kerberos.token.validade.horas=24
